name: American International Academy of the Andes
favicon: null
layout_spectrum: 0.75875
typography_spectrum: 0.5594509013462812
title: AIAAndes
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0c070d'
    - '#fffedf'
    - '#d9a9a5'
    - '#906d74'
    - '#7a1228'
  brandStrength: 0.5
  lightness: 0.4147791776340455
  saturation: 0.4469587591011077
  rhythmicContrast: 0.5358997874427587
purpose: []
